### ISSUE TITLE
Compilation error: 'ARRAY_SIZE_NOTE_C5_TO_C7_PENTATONIC' was not declared in this scope

### ISSUE THREAD

**Issue by RandoSY** [ArminJo/Arduino-RobotCar#4]
Had to dig up my own pitches.h and am seeing this error ...

Compilation error: 'ARRAY_SIZE_NOTE_C5_TO_C7_PENTATONIC' was not declared in this scope

Suggestions?

Thanks ...

**Comment by ArminJo** [comment]
Sorry, I added the missing pitches.h
